### ISSUE TITLE
"Packed Images" test doesn't ignore the "Viewer Node" image

### ISSUE THREAD

**Issue by RobinPeutlschmid** [kiraacorsac/PIGEOnS#2]
[PackedImagesIssueBlend.zip](https://github.com/user-attachments/files/17228351/PackedImagesIssueBlend.zip)
When the add-on is looking for unpacked images in the scene, it is also looking for the "Viewer Node" image which cannot be packed.

**Comment by kiraacorsac** [comment]
Fixed in 1.2.0
